"""products_raw and products

Сырой и нормализованный слои продуктов (раздел 7 брифа).

Сгенерировано автогенерацией и проверено вручную. Что проверялось отдельно:

* `postgresql_using='gin'` для `ix_products_categories_tags` — индекс объявлен
  в `__table_args__` модели, поэтому автогенератор перенёс его правильно;
  на btree пересечение массивов не работало бы;
* `ARRAY(String)` и `JSONB` оформлены диалектными типами Postgres, а не
  обобщёнными;
* `downgrade` снимает индексы и таблицы в обратном порядке, включая GIN
  с тем же `postgresql_using`.

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_raw',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('dump_version', sa.String(length=128), nullable=True),
    sa.Column('rev', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_products_raw'))
    )
    op.create_table('products',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('product_name', sa.String(length=512), nullable=True),
    sa.Column('generic_name', sa.String(length=512), nullable=True),
    sa.Column('brands', sa.String(length=512), nullable=True),
    sa.Column('ingredients_text', sa.String(), nullable=True),
    sa.Column('ingredients_text_lang', sa.String(length=8), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('categories_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('food_groups_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('countries_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('labels_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('nutriscore_grade', sa.String(length=1), nullable=True),
    sa.Column('nutriscore_score', sa.Integer(), nullable=True),
    sa.Column('nova_group', sa.Integer(), nullable=True),
    sa.Column('energy_kcal_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('fat_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('saturated_fat_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('carbohydrates_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('sugars_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('fiber_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('proteins_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('salt_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('sodium_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('fruits_vegetables_nuts_estimate_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('nutrition_score_fr_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('nutrition_data_per', sa.String(length=16), nullable=True),
    sa.Column('has_nutrition_data', sa.Boolean(), nullable=False),
    sa.Column('ingredients_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('additives_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('allergens_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('traces_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('ingredients_analysis_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('ingredients_n', sa.Integer(), nullable=True),
    sa.Column('known_ingredients_n', sa.Integer(), nullable=True),
    sa.Column('unknown_ingredients_n', sa.Integer(), nullable=True),
    sa.Column('additives_n', sa.Integer(), nullable=True),
    sa.Column('unique_scans_n', sa.Integer(), nullable=True),
    sa.Column('popularity_key', sa.BigInteger(), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('rev', sa.Integer(), nullable=True),
    sa.Column('last_modified_t', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['products_raw.code'], name=op.f('fk_products_code_products_raw'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_products'))
    )
    op.create_index('ix_products_categories_tags', 'products', ['categories_tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_products_last_modified_t', 'products', ['last_modified_t'], unique=False)
    op.create_index('ix_products_nova_group', 'products', ['nova_group'], unique=False)
    op.create_index('ix_products_nutriscore_grade', 'products', ['nutriscore_grade'], unique=False)
    op.create_index('ix_products_unknown_ingredients_n', 'products', ['unknown_ingredients_n'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_unknown_ingredients_n', table_name='products')
    op.drop_index('ix_products_nutriscore_grade', table_name='products')
    op.drop_index('ix_products_nova_group', table_name='products')
    op.drop_index('ix_products_last_modified_t', table_name='products')
    op.drop_index('ix_products_categories_tags', table_name='products', postgresql_using='gin')
    op.drop_table('products')
    op.drop_table('products_raw')
    # ### end Alembic commands ###
