"""product_extraction and ingredients_dict

Результаты извлечения и словарь алиасов ингредиентов.

Главное в этой миграции — уникальность по `(code, model_name, prompt_version)`,
а не по `code`. У продукта может быть несколько извлечений разными версиями
промпта и разными моделями; без этого новая версия перетёрла бы старую,
и сравнение версий в M3 стало бы невозможным.

Проверено вручную, помня уроки M1: автогенерация не замечает смену типа
`varchar(n) -> text`, а `Enum` по умолчанию хранит имя члена, а не значение.
Здесь перечислений нет, `unreadable` — обычный BOOLEAN.

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients_dict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.String(length=128), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients_dict')),
    sa.UniqueConstraint('alias', 'lang', name='uq_ingredients_dict_alias_lang')
    )
    op.create_index('ix_ingredients_dict_canonical', 'ingredients_dict', ['canonical_name'], unique=False)
    op.create_table('product_extraction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('source_lang', sa.String(length=8), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('distinct_sugar_forms', sa.Integer(), nullable=False),
    sa.Column('e_additives_count', sa.Integer(), nullable=False),
    sa.Column('ingredients_count', sa.Integer(), nullable=False),
    sa.Column('allergens', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('unreadable', sa.Boolean(), nullable=False),
    sa.Column('model_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_s', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['products.code'], name=op.f('fk_product_extraction_code_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_extraction')),
    sa.UniqueConstraint('code', 'model_name', 'prompt_version', name='uq_product_extraction_code_model_prompt')
    )
    op.create_index('ix_product_extraction_prompt_model', 'product_extraction', ['prompt_version', 'model_name'], unique=False)
    op.create_index('ix_product_extraction_sugar_forms', 'product_extraction', ['distinct_sugar_forms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_extraction_sugar_forms', table_name='product_extraction')
    op.drop_index('ix_product_extraction_prompt_model', table_name='product_extraction')
    op.drop_table('product_extraction')
    op.drop_index('ix_ingredients_dict_canonical', table_name='ingredients_dict')
    op.drop_table('ingredients_dict')
    # ### end Alembic commands ###
